### ISSUE TITLE
replaygain fails to calculate

### ISSUE THREAD

**Issue by Lonsfor** [flathub/org.musicbrainz.Picard#157]
it simply doesn't work for .ogg files and i get this as a terminal output
```
E: 23:34:32,606 /app/lib/python3.9/site-packages/picard/util/thread.run:66: Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/picard/util/thread.py", line 63, in run
    result = self.func()
  File "/home/lothar/.var/app/org.musicbrainz.Picard/config/MusicBrainz/Picard/plugins/replaygain2.zip/replaygain2/__init__.py", line 178, in calculate_replaygain
    raise Exception(f"ReplayGain 2.0: File '{file.filename}' is of unsupported format")
Exception: ReplayGain 2.0: File '/home/lothar/Downloads/untitledfolder/3/Battlejuice - The Gates - 1 The Gates.ogg' is of unsupported format
```

**Comment by phw** [comment]
That's unrelated to the Flatpak package. That's a general issue with the replaygain2 plugin. A fix is prepared at https://github.com/metabrainz/picard-plugins/pull/353
